---
- name: Enable and start auditd
  ansible.builtin.systemd:
    name: "{{ svc_audit[ansible_os_family] | default('auditd') }}"
    enabled: true
    state: started
  when:
    - log_forwarder_linux_install | bool
    - log_forwarder_audit_enabled | bool

- name: Load active audit rules
  ansible.builtin.command: augenrules --load
  changed_when: false
  when:
    - log_forwarder_linux_install | bool
    - log_forwarder_audit_enabled | bool

- name: Enable and start fluent-bit
  ansible.builtin.systemd:
    name: "{{ svc_fluent_bit }}"
    enabled: true
    state: started
  when: log_forwarder_linux_install | bool
...
